### ISSUE TITLE
Currently failing to read fields from Dynamic XFA PDF

### ISSUE THREAD

**Issue by medinm0** [AutomationAnywhere/A2019-PDF_UtilitiesPackage-162554#1]
Currently unable to read the fields from a Dynamic XFA PDF. Only getting the following text: 
```
"Please wait... 
  
If this message is not eventually replaced by the proper contents of the document, your PDF 
viewer may not be able to display this type of document. "
```
Is there something additional that can be done?

**Comment by micahman33** [comment]
Hey @medinm0 

Certain PDF files (dynamic XFA forms) created in Adobe LiveCycle can only be opened in Adobe Reader and Adobe Acrobat. When you try to open these files in other PDF viewers/libraries, then you will get this error message.

Unfortunately, it's not easy remove this message and modify the PDF so that it can be opened in other PDF viewers. The person who created the original form must re-create the form using options that do not restrict which PDF viewers can open and display the file.

Adobe has made the decision that since very few non-Adobe products support these special PDF files, that it is better to show this message -- and require the user to download Adobe Reader or Adobe Acrobat -- than it is to let the PDF viewer try to render the document.

This is not a limitation of Automation Anywhere so much as a limitation of most all PDF libraries (and PDF viewers outside of Reader/Acrobat).
